apiVersion: v2
name: matrix
description: A chart for Matrix.org, includes Synapse, PostgreSQL, and Element.

type: application

version: 1.0.13

# The version of Synapse
appVersion: "1.88.0"

dependencies:
  - name: postgres
    version: "0.2.*"
    repository: https://remram44.github.io/matrix-helm
    condition: postgres.enabled
  - name: element
    version: "1.0.*"
    repository: https://remram44.github.io/matrix-helm
    condition: element.enabled
